# Invidious Viewer 設定ファイル

# Invidiousインスタンス設定
invidious:
  # デフォルトで使用するインスタンス
  default_instance: "https://invidious.snopyta.org"
  
  # 利用可能なインスタンスのリスト（優先順位順）
  # 最初のインスタンスが応答しない場合、次のインスタンスが使用されます
  instances:
    - name: "Snopyta"
      url: "https://invidious.snopyta.org"
      region: "EU"
      description: "Snopytaが提供するインスタンス"
    
    - name: "Invidious.io"
      url: "https://invidious.io"
      region: "US"
      description: "Invidious.ioが提供するインスタンス"
    
    - name: "Yewtu.be"
      url: "https://yewtu.be"
      region: "DE"
      description: "Yewtu.beが提供するインスタンス"
      health: 100
    
    - name: "Nadeko"
      url: "https://inv.nadeko.net"
      region: "CL"
      description: "Nadekoが提供するインスタンス"
      health: 100
    
    - name: "420129.xyz"
      url: "https://id.420129.xyz"
      region: "DE"
      description: "420129.xyzが提供するインスタンス"
      health: 94
    
    - name: "NerdVPN"
      url: "https://invidious.nerdvpn.de"
      region: "UA"
      description: "NerdVPNが提供するインスタンス"
      health: 84
    
    - name: "F5.si"
      url: "https://invidious.f5.si"
      region: "JP"
      description: "F5.siが提供するインスタンス"
      health: 75
    
    - name: "Lekker"
      url: "https://lekker.gay"
      region: "Unknown"
      description: "Lekkerが提供するインスタンス"
      health: 80
    
    - name: "TechnicalVoid"
      url: "https://invidious.technicalvoid.dev"
      region: "Unknown"
      description: "TechnicalVoidが提供するインスタンス"
      health: 80
    
    - name: "Schenkel"
      url: "https://invidious.schenkel.eti.br"
      region: "BR"
      description: "Schenkelが提供するインスタンス"
      health: 80

# アプリケーション設定
app:
  # 視聴履歴の保存日数
  history_days: 30
  
  # ダウンロードディレクトリ
  download_dir: "downloads"
  
  # デフォルトの動画品質（可能な場合）
  # 選択肢: highest, lowest, 720p, 480p, 360p
  default_quality: "720p"
  
  # エラー表示設定
  display_errors: true